Instance:
  Mapping:
    attachedDisk: "disks"
    bootDisk: "disks"
    networkInterface: "networkInterfaces"
    ipv6AccessConfig: "ipv6AccessConfigs"
    accessConfig:  "accessConfigs"
  Exclude:
    - scheduling.locationHint
